name: flutter_lab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  win32: ^5.12.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.6.0
  table_calendar: ^3.0.8 #달력위젯
  device_calendar: ^4.3.3  #디바이스 캘린더 연동
  flutter_speed_dial: ^6.2.0 #FAB확장을 위한 speed dial예시
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.5.3
  location: ^5.0.3
  permission_handler: ^11.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2
  flutter_markdown: ^0.7.7+1
  wakelock_plus: ^1.1.1
  vibration: ^1.7.8
  image_picker: ^1.0.7
  characters: ^1.2.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:


  uses-material-design: true
  assets:
    - assets/
    - .env
